name: Review changes on Dev (Commits/PRs)

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['dev']
    types: [opened, synchronize, reopened]

env:
  WP_MIN_SUPPORTED_VERSION: '6.0'
  PHP_MIN_SUPPORTED_VERSION: '7.4'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-wp-compat-matrix:
    name: "Generate the matrix for wordpress compatibility dynamically"
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.generate_matrix.outputs.matrix }}
    steps:
      - name: "Generate matrix"
        id: generate_matrix
        run: |
          MATRIX_INCLUDE=$( echo "[{\"wordpress\":\"$WP_MIN_SUPPORTED_VERSION\",\"gutenberg\":\"13.6.0\",\"php\":\"$PHP_MIN_SUPPORTED_VERSION\"}]" )
          echo "matrix={\"wordpress\":[\"latest\"],\"gutenberg\":[\"latest\"],\"php\":[\"7.4\"], \"include\":$MATRIX_INCLUDE}" >> $GITHUB_OUTPUT
  phpcs:
    name: PHPCS
    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest' ]
        php-versions: ['7.4','8.0' ,'8.1' ]
        phpunit-versions: ['7.5.20','latest']
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: "Validate composer.json and composer.lock"
        run: composer validate --strict
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          ini-values: "memory_limit=1G"
          coverage: none
          tools: cs2pr
      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"
      - name: Run PHPCS checks
        continue-on-error: true
        run: vendor/bin/phpcs --ignore=*/tests/*,*/data/*,*/assets/* --report-full --report-checkstyle=./phpcs-report.xml
      - name: Git Blame
        continue-on-error: true
        run: vendor/bin/phpcs  -s --report=gitblame --ignore=*/tests/*,*/data/*,*/assets/* .
      - name: Show PHPCS results in PR
        run: cs2pr ./phpcs-report.xml
      - name: Run WordPress Checks
        continue-on-error: true
        run: composer run standards:check